/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module carry_lookahead_adder(a, b, carry_in, sum, carry_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire _57_;
  wire _58_;
  wire _59_;
  wire _60_;
  wire _61_;
  wire _62_;
  wire _63_;
  wire _64_;
  wire _65_;
  wire _66_;
  wire _67_;
  wire _68_;
  wire _69_;
  wire _70_;
  wire _71_;
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  wire [8:0] carry;
  input carry_in;
  wire carry_in;
  output carry_out;
  wire carry_out;
  output [7:0] sum;
  wire [7:0] sum;
  sky130_fd_sc_hd__xnor2_1 _72_ (
    .A(_39_),
    .B(_31_),
    .Y(_49_)
  );
  sky130_fd_sc_hd__xnor2_1 _73_ (
    .A(_47_),
    .B(_49_),
    .Y(_64_)
  );
  sky130_fd_sc_hd__maj3_1 _74_ (
    .A(_39_),
    .B(_31_),
    .C(_47_),
    .X(_50_)
  );
  sky130_fd_sc_hd__xnor2_1 _75_ (
    .A(_40_),
    .B(_32_),
    .Y(_51_)
  );
  sky130_fd_sc_hd__xnor2_1 _76_ (
    .A(_50_),
    .B(_51_),
    .Y(_65_)
  );
  sky130_fd_sc_hd__maj3_1 _77_ (
    .A(_40_),
    .B(_32_),
    .C(_50_),
    .X(_52_)
  );
  sky130_fd_sc_hd__xnor2_1 _78_ (
    .A(_41_),
    .B(_33_),
    .Y(_53_)
  );
  sky130_fd_sc_hd__xnor2_1 _79_ (
    .A(_52_),
    .B(_53_),
    .Y(_66_)
  );
  sky130_fd_sc_hd__maj3_1 _80_ (
    .A(_41_),
    .B(_33_),
    .C(_52_),
    .X(_54_)
  );
  sky130_fd_sc_hd__xnor2_1 _81_ (
    .A(_42_),
    .B(_34_),
    .Y(_55_)
  );
  sky130_fd_sc_hd__xnor2_1 _82_ (
    .A(_54_),
    .B(_55_),
    .Y(_67_)
  );
  sky130_fd_sc_hd__maj3_1 _83_ (
    .A(_42_),
    .B(_34_),
    .C(_54_),
    .X(_56_)
  );
  sky130_fd_sc_hd__xnor2_1 _84_ (
    .A(_43_),
    .B(_35_),
    .Y(_57_)
  );
  sky130_fd_sc_hd__xnor2_1 _85_ (
    .A(_56_),
    .B(_57_),
    .Y(_68_)
  );
  sky130_fd_sc_hd__maj3_1 _86_ (
    .A(_43_),
    .B(_35_),
    .C(_56_),
    .X(_58_)
  );
  sky130_fd_sc_hd__xnor2_1 _87_ (
    .A(_44_),
    .B(_36_),
    .Y(_59_)
  );
  sky130_fd_sc_hd__xnor2_1 _88_ (
    .A(_58_),
    .B(_59_),
    .Y(_69_)
  );
  sky130_fd_sc_hd__maj3_1 _89_ (
    .A(_44_),
    .B(_36_),
    .C(_58_),
    .X(_60_)
  );
  sky130_fd_sc_hd__xnor2_1 _90_ (
    .A(_45_),
    .B(_37_),
    .Y(_61_)
  );
  sky130_fd_sc_hd__xnor2_1 _91_ (
    .A(_60_),
    .B(_61_),
    .Y(_70_)
  );
  sky130_fd_sc_hd__maj3_1 _92_ (
    .A(_45_),
    .B(_37_),
    .C(_60_),
    .X(_62_)
  );
  sky130_fd_sc_hd__xnor2_1 _93_ (
    .A(_46_),
    .B(_38_),
    .Y(_63_)
  );
  sky130_fd_sc_hd__maj3_1 _94_ (
    .A(_46_),
    .B(_38_),
    .C(_62_),
    .X(_48_)
  );
  sky130_fd_sc_hd__xnor2_1 _95_ (
    .A(_62_),
    .B(_63_),
    .Y(_71_)
  );
  assign { carry[8], carry[0] } = { carry_out, carry_in };
  assign _39_ = b[0];
  assign _31_ = a[0];
  assign _47_ = carry_in;
  assign sum[0] = _64_;
  assign _40_ = b[1];
  assign _32_ = a[1];
  assign sum[1] = _65_;
  assign _41_ = b[2];
  assign _33_ = a[2];
  assign sum[2] = _66_;
  assign _42_ = b[3];
  assign _34_ = a[3];
  assign sum[3] = _67_;
  assign _43_ = b[4];
  assign _35_ = a[4];
  assign sum[4] = _68_;
  assign _44_ = b[5];
  assign _36_ = a[5];
  assign sum[5] = _69_;
  assign _45_ = b[6];
  assign _37_ = a[6];
  assign sum[6] = _70_;
  assign _46_ = b[7];
  assign _38_ = a[7];
  assign carry_out = _48_;
  assign sum[7] = _71_;
endmodule
